### ISSUE TITLE
Apples

### ISSUE THREAD

**Issue by KrazyMiner001** [Suyashtnt/JARM-2.0#4]
Add ruby, enchanted ruby, NISGD, and enchanted NISGD apple

**Comment by Suyashtnt** [comment]
why dont u? totallygamerjet has a tutorial on food

**Comment by KrazyMiner001** [comment]
k, just send link to vid don't fee like finding it

**Comment by Suyashtnt** [comment]
https://www.youtube.com/watch?v=44Vri1G5rxA

**Comment by KrazyMiner001** [comment]
btw i will be unable to test if it be working cuz for some reason minecraft doesn't like starting via the InteliJ Idea thing

**Comment by Suyashtnt** [comment]
> 
> 
> btw i will be unable to test if it be working cuz for some reason minecraft doesn't like starting via the InteliJ Idea thing

whats the error?

**Comment by Suyashtnt** [comment]
remember to make it a seperate branch
